domain_path: C:\Users\ELVIS\EE4218-Lab\docs\Lab_2\Lab_2_Files\Lab2_assignment\platform\zynqmp_fsbl\zynqmp_fsbl_bsp
app_src_dir: C:\AMDDesignTools\2025.2\Vitis\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
template: zynqmp_fsbl
lang: c
